version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=T3st!Th1sSh1t!

  wds-minigameshub.web:
    image: wdsminigameshubweb:test
    container_name: wdsminigameshubwebapi
    depends_on:
      - sqlserver
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: Dockerfile